-- Create Albums Table
create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  cover_url text, -- Optional cover image for the album
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Photos Table
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  album_id bigint references public.albums(id) on delete cascade not null,
  url text not null,
  caption text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.albums enable row level security;
alter table public.photos enable row level security;

-- Policies for Albums
create policy "Albums are viewable by everyone."
  on albums for select
  using ( true );

create policy "Admins can insert albums."
  on albums for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update albums."
  on albums for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete albums."
  on albums for delete
  using ( auth.role() = 'authenticated' );

-- Policies for Photos
create policy "Photos are viewable by everyone."
  on photos for select
  using ( true );

create policy "Admins can insert photos."
  on photos for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can delete photos."
  on photos for delete
  using ( auth.role() = 'authenticated' );

-- STORAGE POLICIES (You might need to run these if you create a 'gallery' bucket)
-- Note: You must create a new PUBLIC bucket named 'gallery' in Supabase Storage first.

-- Policy to allow public viewing of storage
-- create policy "Gallery images are publicly accessible."
--   on storage.objects for select
--   using ( bucket_id = 'gallery' );

-- Policy to allow admins to upload
-- create policy "Admins can upload gallery images."
--   on storage.objects for insert
--   with check ( bucket_id = 'gallery' and auth.role() = 'authenticated' );
