-- VIDEOS TABLE
create table public.videos (
  id bigint generated by default as identity primary key,
  youtube_id text not null,
  title text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.videos enable row level security;

-- Policies
create policy "Videos are viewable by everyone."
  on videos for select
  using ( true );

create policy "Admins can insert videos."
  on videos for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update videos."
  on videos for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete videos."
  on videos for delete
  using ( auth.role() = 'authenticated' );
