-- Create Events Table to stop 404 errors
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  date timestamp with time zone not null,
  description text,
  image_url text, -- Optional flyer/image
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.events enable row level security;

-- Policies
create policy "Events are viewable by everyone." on events for select using ( true );
create policy "Admins can insert events." on events for insert with check ( auth.role() = 'authenticated' );
create policy "Admins can update events." on events for update using ( auth.role() = 'authenticated' );
create policy "Admins can delete events." on events for delete using ( auth.role() = 'authenticated' );
