-- Create leaders table
create table if not exists public.leaders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  title text not null,
  image_url text,
  description text -- Optional, keeping it just in case, though the design is simple
);

-- Set up Storage for leader images
insert into storage.buckets (id, name, public)
values ('leaders', 'leaders', true)
on conflict (id) do nothing;

-- RLS Policies for table
alter table public.leaders enable row level security;

create policy "Public can view leaders"
  on public.leaders for select
  using (true);

create policy "Admins can insert leaders"
  on public.leaders for insert
  with check (auth.role() = 'authenticated');

create policy "Admins can update leaders"
  on public.leaders for update
  using (auth.role() = 'authenticated');

create policy "Admins can delete leaders"
  on public.leaders for delete
  using (auth.role() = 'authenticated');

-- RLS Policies for Storage
create policy "Public can view leader images"
  on storage.objects for select
  using ( bucket_id = 'leaders' );

create policy "Admins can upload leader images"
  on storage.objects for insert
  with check ( bucket_id = 'leaders' and auth.role() = 'authenticated' );

create policy "Admins can update leader images"
  on storage.objects for update
  with check ( bucket_id = 'leaders' and auth.role() = 'authenticated' );

create policy "Admins can delete leader images"
  on storage.objects for delete
  using ( bucket_id = 'leaders' and auth.role() = 'authenticated' );
