-- Create events table if it doesn't exist
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  day text not null,
  time text not null,
  description text,
  image_url text, -- URL to the image in storage
  leader_name text, -- New field for event head
  leader_role text, -- New field for leader's role (e.g. "Head of Dept")
  detailed_description text -- New field for the learn more page
);

-- Enable RLS
alter table public.events enable row level security;

-- Policies for events table
create policy "Public can view events" 
  on public.events for select 
  using ( true );

create policy "Admins can insert events" 
  on public.events for insert 
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update events" 
  on public.events for update 
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete events" 
  on public.events for delete 
  using ( auth.role() = 'authenticated' );

-- Note: We will use the existing 'gallery' bucket for event images to simplify storage management,
-- or ensure an 'images' bucket exists. Assuming 'gallery' is fine or we create an 'events' folder in it.
