-- Create calendar_events table
create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  event_date date not null,
  time text,
  location text
);

-- Enable RLS
alter table public.calendar_events enable row level security;

-- Policies
create policy "Public can view calendar_events" 
  on public.calendar_events for select 
  using ( true );

create policy "Admins can insert calendar_events" 
  on public.calendar_events for insert 
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update calendar_events" 
  on public.calendar_events for update 
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete calendar_events" 
  on public.calendar_events for delete 
  using ( auth.role() = 'authenticated' );
