-- Enable Row Level Security
alter default privileges revoke execute on functions from public;

-- PROFILES TABLE
create table public.profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  phone_number text,
  role text,
  updated_at timestamp with time zone
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- SLIDES TABLE
create table public.slides (
  id bigint generated by default as identity primary key,
  src text not null,
  alt text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.slides enable row level security;

create policy "Slides are viewable by everyone."
  on slides for select
  using ( true );

create policy "Admins can insert slides."
  on slides for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can delete slides."
  on slides for delete
  using ( auth.role() = 'authenticated' );

-- MESSAGES TABLE
create table public.messages (
  id bigint generated by default as identity primary key,
  type text not null, -- 'Prayer Request' or 'Testimony'
  name text not null,
  email text not null,
  message text not null,
  read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

create policy "Admins can view all messages."
  on messages for select
  using ( auth.role() = 'authenticated' );

create policy "Anyone can insert messages."
  on messages for insert
  with check ( true );

create policy "Admins can update messages (mark as read)."
  on messages for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete messages."
  on messages for delete
  using ( auth.role() = 'authenticated' );

-- STORAGE BUCKET FOR SLIDES
insert into storage.buckets (id, name)
values ('slides', 'slides');

create policy "Slides images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'slides' );

create policy "Admins can upload slides images."
  on storage.objects for insert
  with check ( bucket_id = 'slides' and auth.role() = 'authenticated' );

create policy "Admins can delete slides images."
  on storage.objects for delete
  using ( bucket_id = 'slides' and auth.role() = 'authenticated' );
