-- 1. Create events table (if not exists)
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  day text not null,
  time text not null,
  description text,
  image_url text,
  leader_name text,
  leader_role text,
  detailed_description text
);

-- 2. Enable RLS
alter table public.events enable row level security;

-- 3. Create Policies (Drop existing first to avoid errors if re-running)
drop policy if exists "Public can view events" on public.events;
drop policy if exists "Admins can insert events" on public.events;
drop policy if exists "Admins can update events" on public.events;
drop policy if exists "Admins can delete events" on public.events;

create policy "Public can view events" 
  on public.events for select 
  using ( true );

create policy "Admins can insert events" 
  on public.events for insert 
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update events" 
  on public.events for update 
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete events" 
  on public.events for delete 
  using ( auth.role() = 'authenticated' );

-- 4. Seed Data (Insert the default events)
-- We use ON CONFLICT DO NOTHING to avoid duplicates if you run this multiple times, 
-- assuming 'id' is preserved. If not, we just insert. 
-- Since 'id' is identity, we can force it or just rely on title/day uniqueness if we added constraint.
-- For simplicity, we will just insert if table is empty.

insert into public.events (title, day, time, description, detailed_description, leader_name, leader_role)
select 'English Service', 'Sunday', '6:30 AM - 9:00 AM', 'Start your week with our English worship service.', 'Join us for a spirit-filled English service where we worship, praise, and dive deep into the Word of God.', 'Rev. John Doe', 'Head Pastor'
where not exists (select 1 from public.events where title = 'English Service');

insert into public.events (title, day, time, description, detailed_description)
select 'Twi Service', 'Sunday', '9:00 AM - 12:00 PM', 'Join our vibrant Twi speaking service.', 'Experience the power of God in our vernacular service with intense worship and prayers.'
where not exists (select 1 from public.events where title = 'Twi Service');

insert into public.events (title, day, time, description, detailed_description)
select 'Men''s Movement', 'Monday', '6:00 PM - 8:00 PM', 'Fellowship and growth for men.', 'A time for men to gather, encourage one another, and grow in their spiritual walk and leadership roles.'
where not exists (select 1 from public.events where title = 'Men''s Movement');

insert into public.events (title, day, time, description, detailed_description)
select 'Women''s Movement', 'Tuesday', '6:00 PM - 8:00 PM', 'Empowering women in faith and life.', 'Women gathering to support each other, pray, and learn how to apply biblical principles in their daily lives.'
where not exists (select 1 from public.events where title = 'Women''s Movement');

insert into public.events (title, day, time, description, detailed_description)
select 'Bible Studies', 'Wednesday', '6:00 PM - 8:00 PM', 'Deep dive into the Word of God.', 'Interactive sessions where we study the scriptures in depth to understand God''s will and apply it.'
where not exists (select 1 from public.events where title = 'Bible Studies');

insert into public.events (title, day, time, description, detailed_description)
select 'Youth Service', 'Thursday', '6:00 PM - 8:00 PM', 'Dynamic service for the next generation.', 'A vibrant service tailored for the youth, featuring energetic worship, relevant talks, and fellowship.'
where not exists (select 1 from public.events where title = 'Youth Service');
